name: Daily Deployment for SEA

on:
  workflow_dispatch:	

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 week'

  create-pull-request-to-dev-merged: #Create PR from atedu-dev -> atedu-dev-merged
    runs-on: ubuntu-latest
    if: success()
    needs: [remove-old-artifacts]
    env:
      CI: false
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with: { ref: dev }
        
      - name: extract git commits data
        uses: rlespinasse/git-commit-data-action@v1
        
      - name: print git commit data
        run: |
          echo "Get commit info"
          echo " - ${{ env.GIT_COMMIT_SHA }}"
          echo " - ${{ env.GIT_COMMIT_SHORT_SHA }}"
          echo "Get author info"

      - name: create a pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: 'dev'
          base: main
          title: 'Auto PR for schedule deployment'
          reviewers: octocat
          assignees: octocat
          body: This is a scheduled auto PR creation
          token: ${{ secrets.GITHUB_TOKEN  }}  
          
      - name: check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
