name: Daily Deployment for SEA

on:
  schedule:
    - cron: '*/5 * * * *'
    
  workflow_dispatch:  
  
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 week'

  create-pull-request-to-dev-merged: #Create PR from atedu-dev -> atedu-dev-merged
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
    if: success()
    needs: [remove-old-artifacts]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with: { ref: dev }
        
      - name: create pull request        
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "👑 *An automated PR*"
          pr_reviewer: octocat
          pr_draft: true
