name: Daily Deployment for SEA

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 week'

  create-pull-request-to-dev-merged: #Create PR from atedu-dev -> atedu-dev-merged
    runs-on: ubuntu-latest
    if: success()
    needs: [remove-old-artifacts]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with: { ref: dev }
        
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .
          
      - name: set autopep8 branch name
        id: vars
        run: echo ::set-output name=branch-name::"autopep8-patches/${{ github.head_ref }}"
        
      - name: create pull request
        if: steps.autopep8.outputs.exit-code == 2
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: autopep8 action fixes
          title: Fixes by autopep8 action
          body: This is an auto-generated PR with fixes by autopep8.
          labels: autopep8, automated pr
          branch: ${{ steps.vars.outputs.branch-name }}
      - name: fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1

